# Generated by Django 3.0.7 on 2021-06-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_alter_portfolio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Binance', 'Binance'), ('Kuobi', 'Kuobi'), ('FTX', 'FTX'), ('Other', 'Other')], default='Other', max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortFolio')),
            ],
            options={
                'verbose_name_plural': 'echanges',
            },
        ),
    ]
