# Generated by Django 3.0.7 on 2021-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210618_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('Binance', 'Binance'), ('Kuobi', 'Kuobi'), ('FTX', 'FTX'), ('Other', 'Other')], max_length=50),
        ),
    ]
