# Generated by Django 3.0.7 on 2021-06-17 12:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0002_exchange_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_auto_20210616_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 41, 42, 76383, tzinfo=utc))),
                ('amount', models.IntegerField()),
                ('paire', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('change', 'change')], default='buy', max_length=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortFolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'assets',
            },
        ),
    ]
