# Generated by Django 3.0.7 on 2021-06-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('exchange', '0001_initial'),
        ('portfolio', '0002_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange'),
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortFolio'),
        ),
    ]
