# Generated by Django 3.0.7 on 2021-06-17 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210617_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 45, 25, 100008, tzinfo=utc)),
        ),
    ]
