# Generated by Django 3.0.7 on 2021-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='paire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('change', 'change')], default='buy', max_length=20),
        ),
    ]
