# Generated by Django 3.0.7 on 2021-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210617_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
