# Generated by Django 3.0.7 on 2021-06-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=50)),
                ('graphTime', models.CharField(choices=[('all', 'all'), ('24h', '24h')], default='all', max_length=50)),
                ('langage', models.CharField(choices=[('en', 'en'), ('fr', 'fr')], default='en', max_length=50)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('CHF', 'CHF')], default='USD', max_length=50)),
                ('defaultFolio', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
