# Generated by Django 3.0.7 on 2021-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210617_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='theme',
            field=models.CharField(default='light', max_length=50),
        ),
    ]
