# Generated by Django 3.0.7 on 2021-06-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210617_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=50),
        ),
    ]
