# Generated by Django 3.0.7 on 2021-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210617_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('CHF', 'CHF')], default='USD', max_length=150),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='graphTime',
            field=models.CharField(choices=[('all', 'all'), ('24h', '24h')], default='all', max_length=150),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='langage',
            field=models.CharField(choices=[('en', 'en'), ('fr', 'fr')], default='en', max_length=150),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=150),
        ),
    ]
